### PR TITLE
pip install pyasn1-modules directly

### LINKED ISSUE #131: packit-service-fedmsg:  The 'pyasn1<0.5.0,>=0.4.6' distribution was not found
```
Traceback (most recent call last):
--
  | File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 578, in _build_master
  | ws.require(__requires__)
  | File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 895, in require
  | needed = self.resolve(parse_requirements(requirements))
  | File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
  | raise VersionConflict(dist, req).with_context(dependent_req)
  | pkg_resources.ContextualVersionConflict: (pyasn1 0.3.7 (/usr/lib/python3.7/site-packages), Requirement.parse('pyasn1<0.5.0,>=0.4.6'), {'pyasn1-modules'})
  |  
  | During handling of the above exception, another exception occurred:
  |  
  | Traceback (most recent call last):
  | File "/usr/local/bin/packit-service", line 6, in <module>
  | from pkg_resources import load_entry_point
  | File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3112, in <module>
  | @_call_aside
  | File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3096, in _call_aside
  | f(*args, **kwargs)
  | File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3125, in _initialize_master_working_set
  | working_set = WorkingSet._build_master()
  | File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 580, in _build_master
  | return cls._build_from_requirements(__requires__)
  | File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 593, in _build_from_requirements
  | dists = ws.resolve(reqs, Environment())
  | File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 781, in resolve
  | raise DistributionNotFound(req, requirers)
  | pkg_resources.DistributionNotFound: The 'pyasn1<0.5.0,>=0.4.6' distribution was not found and is required by pyasn1-modules
```

### PR DESCRIPTION
**Pull request by jpopelka**
Fixes #131

### CODE REVIEW

**Comment by jpopelka** [comment]
[test]

**Comment by TomasTomecek** [comment]
This is super-weird.

**Comment by jpopelka** [comment]
better patches are welcome

**Comment by TomasTomecek** [comment]
does fedmsg pod work with this change?

**Comment by jpopelka** [comment]
> does fedmsg pod work with this change?

no, it fails on missing/incomplete fedmsg config, but that's different story

**Comment by TomasTomecek** [comment]
```
Traceback (most recent call last):
  File "/usr/local/bin/packit-service", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3112, in <module>
    @_call_aside
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3096, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3125, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 580, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 593, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pyasn1 0.3.7 (/usr/lib/python3.7/site-packages), Requirement.parse('pyasn1<0.5.0,>=0.4.6'), {'pyasn1-modules'})
```
I am getting this now -_-

**Comment by jpopelka** [comment]
Weird, `docker-compose up packit-fedmsg` seems to work now, deploying in local oc cluster results in
```python
File "/usr/local/lib/python3.7/site-packages/fedmsg/config.py", line 609, in load_config
  raise ValueError("No config value 'endpoints' found.")
```
No idea what other config (than the one added in last commit) do I miss.

**Comment by jpopelka** [comment]
Superseded by #147

**Pull request closed without merging**
