### PR TITLE
Make queue for fedora messaging durable

### PR DESCRIPTION
**Pull request by dhodovsk**
Related to: https://github.com/packit-service/packit-service/issues/221
Feel free to reject if you know of a reason this might break stuff.

### CODE REVIEW

**Comment by jpopelka** [comment]
No idea how it works, let's wait for @rpitonak

**Comment by jpopelka** [comment]
We set it also in [the fedora-messaging config](https://gitlab.cee.redhat.com/user-cont/packit-service/blob/master/secrets/stg/fedora.toml#L37) so I'm wondering which one takes precedence.

**Comment by jpopelka** [comment]
So I tried to set that to `True` and it doesn't seem to work for me:

```
[WARNING pika.channel] Received remote Channel.Close (406): "PRECONDITION_FAILED - inequivalent arg 'durable' for queue '36C4424F-5FA4-4DE1-B898-A05AD6F0CB03' in vhost '/public_pubsub': received 'true' but current is 'false'" on <Channel number=1 OPEN conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncSSLTransport object at 0x7f6e831c63d0> params=<URLParameters host=rabbitmq.fedoraproject.org port=5671 virtual_host=/public_pubsub ssl=True>>>
[INFO fedora_messaging._session] Channel <Channel number=1 CLOSED conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncSSLTransport object at 0x7f6e831c63d0> params=<URLParameters host=rabbitmq.fedoraproject.org port=5671 virtual_host=/public_pubsub ssl=True>>> closed (406): PRECONDITION_FAILED - inequivalent arg 'durable' for queue '36C4424F-5FA4-4DE1-B898-A05AD6F0CB03' in vhost '/public_pubsub': received 'true' but current is 'false'
```

**Comment by TomasTomecek** [comment]
:(

it would make sense to look how fedora infra projects set up their queues

**Comment by jpopelka** [comment]
> So I tried to set that to `True` and it doesn't seem to work for me:

That was because I tried to connect to already existing queue with different `durable` arg.
Using a new queue uuid works OK.

Anyway, we don't set it in code [anymore](https://github.com/packit-service/packit-service/pull/234) so I'll create a new PR.

**Pull request closed without merging**
