### PR TITLE
[Dockerfile] FROM fedora:30

### LINKED ISSUE #110: Base service image on f30
[Dockerfile](https://github.com/packit-service/packit-service/blob/master/Dockerfile)

```Dockerfile
FROM registry.fedoraproject.org/f29/httpd:2.4
```

### PR DESCRIPTION
**Pull request by jpopelka**
Fixes #110, #131

### CODE REVIEW

**Comment by TomasTomecek** [comment]
where and how is the httpd build set up? (can't login to hub now)

**Comment by jpopelka** [comment]
It's described on the docker hub page:
```
$ sudo dnf install go-md2man
$ git clone --recurse-submodules https://github.com/sclorg/httpd-container.git
$ cd httpd-container
in 2.4/Dockerfile.fedora
- change FROM f29 -> f30
- don't install yum-utils
$ make build TARGET=fedora VERSIONS=2.4
$ docker tag {IMAGE ID} docker.io/usercont/httpd:2.4
```

**Comment by jpopelka** [comment]
> I would also prefer to get rid of scl image and build our own

Do you mean `scl image` or `scl Dockerfile`?
We use [their Dockerfile](https://github.com/sclorg/httpd-container/blob/master/2.4/Dockerfile.fedora), but build [our own image](https://cloud.docker.com/u/usercont/repository/docker/usercont/httpd).

**Comment by rpitonak** [comment]
> > I would also prefer to get rid of scl image and build our own
> 
> Do you mean `scl image` or `scl Dockerfile`?
> We use [their Dockerfile](https://github.com/sclorg/httpd-container/blob/master/2.4/Dockerfile.fedora), but build [our own image](https://cloud.docker.com/u/usercont/repository/docker/usercont/httpd).

I meant to use our own Dockerfile. Main point is that I would still leave #110 open.

**Comment by jpopelka** [comment]
Ok, I'll ask you the same question I asked Tomas: "For what reasons?"!

Should I copy their Dockerfile into our repo so you can consider it "our" Dockerfile?
What's the problem with the sclorg Dockerfile?

Can you please answer in #110 se we have the discussion in one place? thanks

**Comment by phracek** [comment]
I guess the main reason was to get rid of the SCL image and use the Fedora image with httpd package. No SCL functionality, like s2i.

**Comment by phracek** [comment]
The reason is described here https://github.com/packit-service/packit-service/issues/110#issuecomment-534727043

**Comment by jpopelka** [comment]
Ok, got it.
I'll try to put httpd directly into our image.

**Comment by jpopelka** [comment]
grr, still no luck
```
 (13)Permission denied: AH00072: make_sock: could not bind to address [::]:443
 (13)Permission denied: AH00072: make_sock: could not bind to address 0.0.0.0:443
 no listening sockets available, shutting down
 AH00015: Unable to open logs
```

**Comment by jpopelka** [comment]
Ready for review

**Comment by jpopelka** [comment]
> have you tried to deploy it into OpenShift cluster

Yes, thanks for the review. I'm merging now, keep fingers crossed :-)

**Comment by TomasTomecek** [comment]
Very nice! thank you for doing this.

**Pull request merged**
