### PR TITLE
Fix testing farm result mapping

### LINKED ISSUE #504: Fix the handling with testing farm results
When we get the results from testing farm, we do not process them correctly:
`[2020-03-17 16:08:07,532: WARNING/ForkPoolWorker-1] There is no handler for testing_farm_results event.`
`16:08:07.533 jobs.py           DEBUG  All jobs finished!`

Therefore the PR statuses are not updated.

### PR DESCRIPTION
**Pull request by lachmanfrantisek**
- Map testing_farm_result to pull_request.
- Fixes #504

### CODE REVIEW

**Comment by lachmanfrantisek** [comment]
recheck

**Comment by lachmanfrantisek** [comment]
For the third time..;(

**Comment by jpopelka** [comment]
Only my failing internet connection has saved your PR from being rage-merged by me :-)

**Comment by lachmanfrantisek** [comment]
recheck

**Pull request merged**
