### PR TITLE
Copr targets not need to be specified

### PR DESCRIPTION
**Pull request by lachmanfrantisek**
We don't need the targets in the metadata for copr build.

- See the `build_chroots`/`test_chroots` properties of the `BaseBuildJobHelper`.
- I've renamed the relevant test file to match the current naming.

### CODE REVIEW

**Comment by TomasTomecek** [comment]
okay, your precommit job fails on the same thing as in mine PR:
```
2020-02-26 14:18:38.378011 | TASK [Run it]
2020-02-26 14:18:38.983718 | test-node | [INFO] Initializing environment for https://github.com/psf/black.
2020-02-26 14:18:40.379332 | test-node | [INFO] Initializing environment for https://github.com/prettier/prettier.
2020-02-26 14:18:42.636441 | test-node | [INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
2020-02-26 14:18:43.637432 | test-node | [INFO] Initializing environment for https://gitlab.com/pycqa/flake8.
2020-02-26 14:18:45.151013 | test-node | [INFO] Initializing environment for https://github.com/pre-commit/mirrors-mypy.
2020-02-26 14:18:45.976963 | test-node | [INFO] Initializing environment for https://github.com/packit-service/pre-commit-hooks.
2020-02-26 14:18:46.867616 | test-node | [INFO] Initializing environment for https://github.com/packit-service/requre.
2020-02-26 14:18:47.863610 | test-node | [INFO] Installing environment for https://github.com/psf/black.
2020-02-26 14:18:47.863693 | test-node | [INFO] Once installed this environment will be reused.
2020-02-26 14:18:47.863704 | test-node | [INFO] This may take a few minutes...
2020-02-26 14:18:52.313923 | test-node | An unexpected error has occurred: CalledProcessError: command: ('/home/zuul-worker/.cache/pre-commit/repo47iuxo14/py_env-python3.6/bin/python', '/home/zuul-worker/.cache/pre-commit/repo47iuxo14/py_env-python3.6/bin/pip', 'install', '.')
2020-02-26 14:18:52.314151 | test-node | return code: 1
2020-02-26 14:18:52.314173 | test-node | expected return code: 0
2020-02-26 14:18:52.314189 | test-node | stdout:
2020-02-26 14:18:52.314196 | test-node |     Processing /home/zuul-worker/.cache/pre-commit/repo47iuxo14
2020-02-26 14:18:52.314202 | test-node |       Installing build dependencies: started
2020-02-26 14:18:52.314207 | test-node |       Installing build dependencies: finished with status 'done'
2020-02-26 14:18:52.314213 | test-node |       Getting requirements to build wheel: started
2020-02-26 14:18:52.314218 | test-node |       Getting requirements to build wheel: finished with status 'done'
2020-02-26 14:18:52.314230 | test-node |         Preparing wheel metadata: started
2020-02-26 14:18:52.314240 | test-node |         Preparing wheel metadata: finished with status 'error'
2020-02-26 14:18:52.314246 | test-node |
2020-02-26 14:18:52.314251 | test-node | stderr:
2020-02-26 14:18:52.314256 | test-node |         ERROR: Command errored out with exit status 1:
2020-02-26 14:18:52.314265 | test-node |          command: /home/zuul-worker/.cache/pre-commit/repo47iuxo14/py_env-python3.6/bin/python /home/zuul-worker/.cache/pre-commit/repo47iuxo14/py_env-python3.6/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmp9wypnuse
2020-02-26 14:18:52.314288 | test-node |              cwd: /tmp/pip-req-build-0xp8cln8
2020-02-26 14:18:52.314299 | test-node |         Complete output (40 lines):
2020-02-26 14:18:52.314304 | test-node |         /home/zuul-worker/.cache/pre-commit/repo47iuxo14/py_env-python3.6/bin/python: No module named pip
```
something's wrong in the zuulland

**Comment by lachmanfrantisek** [comment]
recheck

**Comment by lachmanfrantisek** [comment]
recheck

**Comment by TomasTomecek** [comment]
needs rebase, I merged mine

**Comment by lachmanfrantisek** [comment]
recheck

**Comment by lachmanfrantisek** [comment]
recheck

**Comment by lachmanfrantisek** [comment]
recheck

**Pull request merged**
