### PR TITLE
postgres: filter PR's by project ID

### PR DESCRIPTION
**Pull request by dhodovsk**
Resolves https://sentry.io/share/issue/d02a242a9d6d4584b0c41d0296b12dfd/

### CODE REVIEW

**Comment by TomasTomecek** [comment]
I'll fix #434 and create tests
recheck

**Comment by dhodovsk** [comment]
I added the test - but since requre is down I had no way to test it...

**Comment by dhodovsk** [comment]
Or @TomasTomecek give me a minute please so I can finish it

**Comment by TomasTomecek** [comment]
> Or @TomasTomecek give me a minute please so I can finish it

never

**Comment by TomasTomecek** [comment]
I usually run the tests_requre/test_db tests using postgres from docker-compose (by doing export on all the required env vars)

**Comment by TomasTomecek** [comment]
Your test is better than mine https://github.com/packit-service/packit-service/pull/441

**Comment by dhodovsk** [comment]
But mine still doesn't pass, so if you have it done and passing, though cleptonless, I close this :)

**Comment by TomasTomecek** [comment]
oki, carrying your commit then in #441

**Pull request closed without merging**
