### PR TITLE
catch exceptions using sentry

### PR DESCRIPTION
**Pull request by TomasTomecek**

### CODE REVIEW

**Comment by TomasTomecek** [comment]
> Looks differently then what we use in frambo (`sentry-sdk` vs. `raven`), but I believe you this is the latest-greatest.

> Raven is the legacy Python client for Sentry (getsentry.com) — replaced by sentry-python https://sentry.io

**Comment by jpopelka** [comment]
Should we change also our [frambo code](https://github.com/user-cont/frambo/blob/master/frambo/celery_app.py#L20) then?

**Comment by TomasTomecek** [comment]
> Should we change also our [frambo code](https://github.com/user-cont/frambo/blob/master/frambo/celery_app.py#L20) then?

up to you, ain't touching that

**Comment by jpopelka** [comment]
I was just asking for your opinion, whether you think it's worth changing or we can leave it as it is.

**Comment by TomasTomecek** [comment]
> I was just asking for your opinion, whether you think it's worth changing or we can leave it as it is.

I'd leave it if it works. Especially since we're using the internal instance.

**Pull request merged**
