### PR TITLE
/packit build alias

### PR DESCRIPTION
**Pull request by lachmanfrantisek**
- Allow '/packit build' to trigger the copr-build as well.

### CODE REVIEW

**Comment by TomasTomecek** [comment]
it's `/` right? not `\`

**Comment by lachmanfrantisek** [comment]
> * this needs docs, obviously

:+1: 

> * should we advertise in the build-failed-you-need-retrigger comment this over `copr-build`?

Good point.

- `build`: When there is no `copr-build` defined and if it is built because of the tests.
  - (="I don't want to know anything about copr." workflow)
- `copr-build`: When there is a `copr-build` defined in the jobs.
  - (="I am interested in copr." workflow)
> it's `/` right? not `\`

Thanks, the wrong slash is only in the git message and PR title.

**Comment by lachmanfrantisek** [comment]
- About the docs: @TomasTomecek, you mean `packit.dev` documentation, right?
- About the re-trigger message: Can we change that when there will be support for defining tests without `copr-build` jobs?

**Comment by TomasTomecek** [comment]
>     * `build`: When there is no `copr-build` defined and if it is built because of the tests.
>       
>       * (="I don't want to know anything about copr." workflow)
> 
>     * `copr-build`: When there is a `copr-build` defined in the jobs.
>       
>       * (="I am interested in copr." workflow)

sounds good!

>     * About the docs: @TomasTomecek, you mean `packit.dev` documentation, right?

yep
 
>     * About the re-trigger message: Can we change that when there will be support for defining tests without `copr-build` jobs?

sounds good! would be nice to track that request somewhere

**Comment by lachmanfrantisek** [comment]
> sounds good! would be nice to track that request somewhere

I'll create a new issue.

**Pull request merged**
