### PR TITLE
Remove incorrect/unused/redundant event-related tests parts

### PR DESCRIPTION
**Pull request by jpopelka**

### CODE REVIEW

**Comment by TomasTomecek** [comment]
hm, the CI job is timing out

**Comment by jpopelka** [comment]
> hm, the CI job is timing out

We should call you "Lightning" :-) (That's what Rado has been trying to solve since Monday)

**Comment by TomasTomecek** [comment]
but the failure in this job looked different than the one I was seeing before

**Comment by rpitonak** [comment]
> but the failure in this job looked different than the one I was seeing before

Yes because logs are not displayed when the test job fails. It is fixed in #254

**Pull request merged**
