### PR TITLE
mach ordnung in Makefile

### PR DESCRIPTION
**Pull request by jpopelka**

### CODE REVIEW

**Comment by jpopelka** [comment]
> [localhost] TASK: wait for tests to finish (debug)> User interrupted execution
> make: *** [Makefile:50: check-inside-openshift-zuul] Error 99

recheck

**Comment by jpopelka** [comment]
recheck

**Comment by jscotka** [comment]
please rebase it on top of master, to check if tests are wokring well in your case

**Comment by jpopelka** [comment]
no brave makefileista?

**Pull request merged**
