### PR TITLE
Remove notify from JobConfig

### PR DESCRIPTION
**Pull request by lbarcziova**

### CODE REVIEW

**Comment by TomasTomecek** [comment]
the pre-commit failure seems unrelated to me

**Comment by lachmanfrantisek** [comment]
> the pre-commit failure seems unrelated to me

It was not catched [here](https://github.com/packit-service/packit-service/pull/256). Can you please fix that here or in the new PR?

**Comment by jscotka** [comment]
> > the pre-commit failure seems unrelated to me
> 
> It was not catched [here](https://github.com/packit-service/packit-service/pull/256). Can you please fix that here or in the new PR?

I've added fix of pre-comit to my PR: https://github.com/packit-service/packit-service/pull/263
But I can remove it if it will be fixed here

**Comment by TomasTomecek** [comment]
I picked commit from this PR in my PR #261, closing this one then

**Pull request closed without merging**
