### PR TITLE
[zuul] test zuul connection

### PR DESCRIPTION
**Pull request by rpitonak**
Hi, @morucci I couldn't find a way how to open a request in the software factory.

Is this config and enabled GitHub app everything that we need? Sorry for bothering you again but Tomas and Honza are on PTO so I couldn't ask them directly.

### CODE REVIEW

**Comment by morucci** [comment]
Hi @rpitonak, yes your PR is ok, from the SF side a change is also needed https://softwarefactory-project.io/r/16054/. Once approved and merged, Zuul will listen to packit-service events, so by commenting "recheck" on the PR comment Zuul should trigger the noop job.

Fill free to ping @TristanCacqueray if needed. I'm on PTO today as well ;)

**Comment by rpitonak** [comment]
@morucci awesome! thank you for the response, and sorry for interrupting your PTO :)

**Comment by rpitonak** [comment]
recheck

**Comment by rpitonak** [comment]
Merging and going to create a follow-up PR.

**Pull request merged**
