### PR TITLE
Fix CI

### LINKED ISSUE #231: when tests fail, there is no way to figure out what went wrong
This is coming from a grooming meeting and initiated by @jscotka 

https://github.com/packit-service/packit-service/issues/210

Get logs from the testing pod and print them, especially the whole output of pytest.

### PR DESCRIPTION
**Pull request by rpitonak**
Fixes #231 also.

### CODE REVIEW

**Comment by rpitonak** [comment]
Tests are passing for me locally. @jscotka the error in CI is:

```
requre.exceptions.PersistentStorageException: Keys not in storage:/src-packit-service/tests_requre/test_data/test_copr/tests_requre.openshift_integration.test_copr.Copr.test_submit_copr_build_pr_event.yaml ['unittest.case', 'tests_requre.openshift_integration.test_copr', 'packit_service.worker.jobs', 'packit_service.service.events', 'packit.config.package_config', 'ogr.services.github.project', 'ogr.services.github_tweak', 'requests.api', 'requests.sessions', 'requre.objects', 'requests.sessions', 'send']"
```

**Comment by rpitonak** [comment]
recheck

**Comment by jpopelka** [comment]
rebase due to #244

**Comment by rpitonak** [comment]
closing in favor of #254

**Pull request closed without merging**
